### ISSUE TITLE
about question 9

### ISSUE THREAD

**Issue by llccing** [sudheerj/vuejs-interview-questions#4]
this  [demo](https://codepen.io/llccing/pen/aMPbWd?editors=1010) for question 9。
you answer is good to me, but i don't what scenarios may cause problem. 

if you know please tell me.

**Comment by sudheerj** [comment]
Can you describe about the issue? The question no.9 is already showing that specific scenario.

**Comment by llccing** [comment]
sorry，you’re right. I don’t really understand your meaning before.
