### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by whc2001** [sudheerj/vuejs-interview-questions#44]
https://github.com/sudheerj/vuejs-interview-questions/blob/ac0b27f4625fb76c09d0007177b83041d60f1884/README.md?plain=1#L713-L720

should be `vm.user.name`

**Comment by sudheerj** [comment]
@whc2001 Thanks. Can you create it as a PR?

**Comment by sudheerj** [comment]
Fixed anyway. Thanks

**Comment by whc2001** [comment]
Ah sorry I didn't notice the notification. Thanks a lot for the awesome work!
